### ISSUE TITLE
FS.h not found error when compiling your touchpad example in the readme file

### ISSUE THREAD

**Issue by HaidiZhou** [schreibfaul1/ESP32-TFT-Library-ILI9341-HX8347D#4]
Dear schreibfaul1,

I just ran the example code that you gave it on your description page, which is to test the touchpad of Waveshare 2.8 TFT with TP, I ran it on the Arduino IDE and came up with FS.h not found problems, I copied the error message as follows:

_Arduino: 1.8.7 (Windows Store 1.8.15.0) (Windows 10), Board: "Arduino/Genuino Uno"

In file included from C:\Users\zhou\Documents\Arduino\test2\test2.ino:3:0:

C:\Users\zhou\Documents\Arduino\libraries\TFT_ILI9341_HX8347_XPT2046/tft.h:5:16: fatal error: FS.h: No such file or directory

compilation terminated.

exit status 1
Fehler beim Kompilieren für das Board Arduino/Genuino Uno._

are there any ways to solve it? Thank you in advance.

**Comment by HaidiZhou** [comment]
For your Information I use the Arduino UNO board connected with a Waveshare 2.8 TFT with TP Arduino shield, its controller is HX8347D, thank you

**Comment by schreibfaul1** [comment]
"SD.h" and "FS.h" are ESP32 system libraries. They are not used by the touchpad but included in tft.h for read files from SD card.  FS.h is part of the ESP32 package.

**Comment by dd7lp** [comment]
Hallo und Guten Tag, ich bin gerade dabei dein Projekt Miniwebradio nachzubauen.
Ich habe die Schaltung erst einmal auf einem Breadbord verdrahted, als ich die software compilieren wollte 
meckert mein Compiler, er findet die Die "C-Datei"  ---  font.h --- nicht. Ich habe alle Dateien nach deinen Angaben in das Projektverzeichnis gebracht, aber die font.h kann ich nirgend finden.
Vielleicht hast du eine Lösung für mich, es wäre sehr freundlich und sehr behilflich
Vielleicht können wir ja einmal in Kontakt treten und du schreibst ein mail an meine Adresse meine mail wäre dd7lp at t-online.de
![fonts-h-jpg](https://user-images.githubusercontent.com/11967091/48716751-4bce9480-ec18-11e8-9dde-418f9220552d.jpg)

mit freundlichen Grüßen von Husum an der nordsee
Christian
