### ISSUE TITLE
SetFontSize kills memory rapidly

### ISSUE THREAD

**Issue by luwre53** [schreibfaul1/ESP32-TFT-Library-ILI9341-HX8347D#5]
Iused this driver and understand that the use of SetFontSize kills flash memory rapidly.

**Comment by schreibfaul1** [comment]
Fonts needed much space in heap. If you need more memory change partition scheme (e.g. HugeApp)

**Comment by luwre53** [comment]
Thanks for pointing on the partition, but changed it by my self. You didn't use pointer for the set size so it will load more at every time. I used a pointer and it works now perfect. Thanks for you response. 

Sent from Yahoo Mail on Android 
 
  On Sat, 14 Sep 2019 at 11:33, Wolle<notifications@github.com> wrote:   
Fonts needed much space in heap. If you need more memory change partition scheme (e.g. HugeApp)
