### ISSUE TITLE
Not USE GPIO 32 and 33

### ISSUE THREAD

**Issue by MagISTRaESP** [schreibfaul1/ESP32-TFT-Library-ILI9341-HX8347D#7]
In file tft.h change 
//------------TFT-------------------

    	inline int minimum(int a, int b){if(a < b) return a; else return b;}
        inline void TFT_DC_HIGH() {GPIO.out_w1ts = (1 << TFT_DC);}
    	inline void TFT_DC_LOW()  {GPIO.out_w1tc = (1 << TFT_DC);}
    	inline void TFT_CS_HIGH() {GPIO.out_w1ts = (1 << TFT_CS);}
    	inline void TFT_CS_LOW()  {GPIO.out_w1tc = (1 << TFT_CS);}

Change to : 

    	inline int minimum(int a, int b){if(a < b) return a; else return b;}
      inline void TFT_DC_HIGH() {if (TFT_DC < 32) {GPIO.out_w1ts = (1 << TFT_DC);} else {GPIO.out1_w1ts.data = (1 << (TFT_DC - 32));}}
      inline void TFT_DC_LOW()  {if (TFT_DC < 32) {GPIO.out_w1tc = (1 << TFT_DC);} else {GPIO.out1_w1tc.data = (1 << (TFT_DC - 32));}}
    	inline void TFT_CS_HIGH() {if (TFT_CS < 32) {GPIO.out_w1ts = (1 << TFT_CS);} else {GPIO.out1_w1ts.data = (1 << (TFT_CS - 32));}}
    	inline void TFT_CS_LOW()  {if (TFT_CS < 32) {GPIO.out_w1tc = (1 << TFT_CS);} else {GPIO.out1_w1tc.data = (1 << (TFT_CS - 32));}}

**Comment by schreibfaul1** [comment]
Thanks, I did not know that GPIO.out1_w1ts exists.
