### ISSUE TITLE
I think the color was not right!

### ISSUE THREAD

**Issue by imliubo** [schreibfaul1/ESP32-TFT-Library-ILI9341-HX8347D#9]
Hi,
You did a great job!I test you library for HX8347D,I found a very strange problem.The color displayed on the display does not seem right.
    
![image](https://user-images.githubusercontent.com/26544331/64919183-5fb43a00-d7da-11e9-9211-92b3dc2e5ec6.png)
I want the screen fill with red color,so I use this code:
```C
tft.fillScreen(tft.color565(0,0,255));
```
But I got this :
![image](https://user-images.githubusercontent.com/26544331/64919221-bfaae080-d7da-11e9-8bc7-5a160d9f58b1.jpg)
I use this [screen](https://www.waveshare.com/product/modules/oleds-lcds/graphic-lcd/2.8inch-resistive-touch-lcd.htm) form WaveShare.

**Comment by schreibfaul1** [comment]
Hello imliubo,
tft.color565(0,0,255) is blue, internally, the color value for blue is shifted 3 positions to the right
`((r & 0xF8) << 8) | ((g & 0xFC) << 3) | ((b & 0xF8) >> 3)` This gives the RGB565 value 0x001F. Blue is also displayed on the Waveshare display. ` tft.fillScreen(TFT_BLUE); ` should be the same result

**Comment by imliubo** [comment]
Hi @schreibfaul1,
Thanks for reply me.I already solved it by change a register value,the register description like picture:
![0U2C9 5AGABP`@6MXDEJ`KJ](https://user-images.githubusercontent.com/26544331/65291797-7c0ff800-db87-11e9-9423-cb4188329b80.jpg)
![image](https://user-images.githubusercontent.com/26544331/65292715-00b04580-db8b-11e9-8f0e-5915f128b624.png)
Now it can be work well!
![image](https://user-images.githubusercontent.com/26544331/65293245-29393f00-db8d-11e9-8e1a-d25646d81a5d.png)
[hx8347d-color-test-gif](https://makingfun.oss-cn-qingdao.aliyuncs.com/Github/justforissues/hx8347d-color-test.gif)

**Comment by schreibfaul1** [comment]
That's weird, if I am set
write `command (0x36); SPI.write (0x00)` on `writeCommand (0x36); SPI.write (0x02)` will change blue to green. Maybe there are different displays?

**Comment by imliubo** [comment]
Hi @schreibfaul1 ,
How can be that...Is the displays driver IC was HX8347-D?I am also very curious, but this setting is useful for me.

**Comment by schreibfaul1** [comment]
Hello imliubo,
I suspect that the TFTs behave differently, the driver ICs are identical
